### ISSUE TITLE
Demo link not working

### ISSUE THREAD

**Issue by samyak24jain** [allenai/document-qa#1]
The link given in the README.md is not working - "A demo of this work can be found at documentqa.allenai.org".

**Comment by chrisc36** [comment]
Its been struggling a bit, but it should be running now:

https://documentqa.allenai.org/

**Comment by chrisc36** [comment]
Actually, the link in the README was wrong, (thanks for pointing this out), now it is fixed.

**Comment by samyak24jain** [comment]
Demo link is working fine now. 
In fact, the links for TriviaQA and AllenNLP also don't seem to be working. Points to the github domain. Same problem as the demo link
