### ISSUE TITLE
Support to  direct PDF doc 

### ISSUE THREAD

**Issue by ajay01994** [allenai/document-qa#10]
Thanks @chrisc36 ,and your Team for making documnet Q/A , currently it is not supporting PDF as direct input , i assume the PDF needs to be processed in the form of <title > and < para > ,using your science parse repo , is there a way to directly take PDF doc as an input with built in pdf processing script in your DOC Q /A or , it will be great if you can do us this favour . Also can you please tell us , that can Doc QA be used as a search engine , apart from traditonal lucene based elastic search and SOLR serach engines .

Thanks
Ajay sahu - Mumbai / BHARAT

**Comment by chrisc36** [comment]
Taking a PDF as input is not something I plan to support, I think that functionality is out-of-scope for this codebase. In theory it shouldn't be too hard to use science parse or pdftotext to get plain text from PDFs that you can then fed into the model, but I would prefer to leave it to clients to decide how best to do that.

document-qa cannot be used as a search engine. Its built to be used on-top of an existing search engine that knows how to select a small number of documents relevant to the question.

**Comment by chrisc36** [comment]
(I deleted your original comment in issue #9 since it makes more sense to discuss this here)

**Comment by ajay01994** [comment]
Yes of, course but  i guess this doc QA can support multiple Doc inputs, as in if the user wants to use its QA on 2 or more Docs ,Now since lets assume the Doc so  made " input " ,is  of the same topic let's say  the topic is "OOP ' Then surely that needs a documnet retrival engine the one like { FACEBOOK RESERACH DR Q/A  } Repo has , for ranking results , please let us know  how does  Documnet  QA , ranks results on multiple doc files foe finding answers .
Thanks

**Comment by chrisc36** [comment]
Right, so for training/testing we have used documents there were provided by the input dataset.

The demo finds documents using a web search similar to the process that TriviaQA [uses] (https://homes.cs.washington.edu/~eunsol/papers/acl17jcwz.pdf).

**Comment by ajay01994** [comment]
okay @chrisc36  i checked the TRIVIA QA  method , as in if you are saying  that the DOC QA   shall be used on top of  any search engine let's say elasticsearch , so, elastic search uses TD-IDF with BOOLEAN functions to find nearest doc and then uses  APACHE TIKA  for relevance , which is more based on keywords , i find it theoreotically  hard as in how TRIVIA QA method would work with  lucene based serach engine , as the duo have totally diffrent method of relevance , so it would be great if you can explain that  thoeoreotically , apart from elastic serach other lucene based engines rely on BM -25 model , which again has a diffrent method ,   so a little bit of confusion is over there , on the other hand  [https://github.com/facebookresearch/DrQA](url) used TD-IDF with bigram  function for relevence  [https://arxiv.org/abs/1704.00051](url) how is TRIVIA QA  better than that in terms of results on search results ?

**Comment by ajay01994** [comment]
i also found some issues with search results   i have provided the screen shot of the same here
![screenshot_21](https://user-images.githubusercontent.com/31235529/32931575-d845ca64-cb8a-11e7-9f8a-a3040035b11c.png)
![screenshot_22](https://user-images.githubusercontent.com/31235529/32931576-d88992bc-cb8a-11e7-9b1d-1a7e67b1bcfa.png)
![screenshot_23](https://user-images.githubusercontent.com/31235529/32931577-d8b4ec0a-cb8a-11e7-9e99-a7cdbc5b2178.png)
 

> The answer is chneging as with just a change of "The " Word  in the query , also the paragraphs cleary indicate as written " The president of India is Shree pranab mukherjee " in its initial first results , so a bit went wrong on results  , it would be great if you could  explain us why is that happening ?

**Comment by chrisc36** [comment]
You should be able to use the model with any kind of search engine that returns documents relevant to the input question. Our work is not about improving the search engine, its about improving the model that is used to process the documents the search engine produces. 

As for the model's output, I can't really offer an explanation. The model is, of course, not perfect and can make mistakes, and its notoriously difficult to understand why the mistakes occur for these kinds of models. We have noticed (as is mentioned in the about page) that confusion about time and what is "current" is a common source of error.

**Comment by ajay01994** [comment]
okay. so i got your point as the  the DOC -QA  is more focussed on improving the model ..Thanks for sharing the insights  i ll try to create a pull request  and add support to pdf doc ...
