### ISSUE TITLE
How was the pre-trained ELMo model trained?

### ISSUE THREAD

**Issue by felixgwu** [allenai/document-qa#13]
Hi Chris,

Could you explain how the pre-trained ELMo model was trained a little bit?
Also, could provide a pointer to the paper that describes this model?
Thanks in advance.

Best,
Felix

**Comment by chrisc36** [comment]
I didn't pre-train the model myself, so I can't give you a lot of details. The ELMo stuff is an implementation of the idea proposed here: (still under review) https://openreview.net/pdf?id=S1p31z-Ab

**Comment by felixgwu** [comment]
Thanks a lot!

**Comment by jasonwbw** [comment]
@chrisc36 could you update any open link now, as the one on openreview is out of date.

**Comment by chrisc36** [comment]
Done!

**Comment by FredericGodin** [comment]
Do you have an example script for training this pretrained model? I have a huge corpus myself..
