### ISSUE TITLE
ResourceExhaustedError: OOM when allocating tensor with shape

### ISSUE THREAD

**Issue by ewagner70** [allenai/document-qa#16]
I've run successfully every script and can run the test-scripts with pre-trained models. But I constantly fail to execute the Training scripts, because I'll get a resouceexhausted error and don't know why, i.e. what to do and to overcome it.
my Environment: ubuntu 16.04, GTX 970, python 3.5
details see attached stdout
[abalata_triviaqa_errors.zip](https://github.com/allenai/document-qa/files/1554782/abalata_triviaqa_errors.zip)

**Comment by chrisc36** [comment]
Its look like the GTX 970 only has 4gb of RAM, and that was simply not sufficient to train the network on. 

The best way to fix this would be to get a GPU with more RAM. Otherwise you could lower the batch size, or possibly the paragraph size, by altering the train script. I can help you do that if needed, the batch size is a parameter in either the `ClusteredBatcher` objects or in the `StratifyParagraphSetsBuilder` objects, depending on what mode you are running in.

**Comment by bdhingra** [comment]
Hi,

I'm also facing OOM issues using this code on a different dataset than TriviaQA / Squad. I would like to limit the maximum paragraph size of the passages. Can you please point me to where in the code I can change this, and what is the default value?

Thanks,
Bhuwan

**Comment by bdhingra** [comment]
I am running the paragraph mode for Squad dataset.

**Comment by ewagner70** [comment]
Thank you, Chris - for the (retrospectively quite obvious) hint! 
I cut the batch size for both functions by 50% and now training's running since hours ...

2nd question to you out of interest/"benchmarking": What environment (OS, HW/CPU/GPU) are you using?
KR Eric

**Comment by chrisc36** [comment]
@bdhingra In general you would have to build your own `TrainingData` object, and then make sure that you truncate the passages before you feed them into the model. If you happen to be using the `squad.DocumentQaTrainingData` you could, for example, override the `preprocess` method and do the truncating there. 

For us, the default value in SQuAD is to just use the entire paragraph as found in the SQuAD source data. For TriviaQA we use the `MergeParagraphs` class, which both merges small paragraphs together and truncates paragraphs to a maximum size depending on the `max_tokens` parameter.

**Comment by bdhingra** [comment]
Thanks @chrisc36. I ended up preprocessing the dataset itself, since that seemed to be the easiest path.

**Comment by chrisc36** [comment]
Everything seems to be covered so I am closing this issue
