### ISSUE TITLE
Latest weights vs best weights

### ISSUE THREAD

**Issue by danishpruthi** [allenai/document-qa#18]
Hi, 

Thanks for making the code available. 

I found that in the triviaQa (web), the best weights are not dumped [1]. In the `docqa/evaluator.py`, if it doesn't find the best weights, it continues with the latest checkpoint. However, that might be suboptimal, especially if the model overfits the data.

[1]. In the `docqa/scripts/ablate_triviaqa.py` the function `get_triviaqa_train_params` doesn't contain `best_weights` as a parameter (contrary to `ablate_squad.py` which does have that parameter, and hence it ends up not saving the best weights). 

Please correct me if I am wrong. 

Now, the issue I am facing is that while I have model dumps for different sizes of training data (something I need for my comparison), I am not able to truly evaluate as the latest weights might be misrepresentative. Given this, I can pick values from the tensorboard, but I read on another thread that those numbers are optimistic since those numbers are computed over a biased set of paragraphs for a given question. What do you recommend I do in such a case?

**Comment by chrisc36** [comment]
That is correct, our original implementation just used the weights at the end of training, so the ablate scripts keep it that way for the sake of correctness. For these models, using the "best weights" often does not make a large difference anyway.

I am afraid I don't have an immediate solution to your problem. For the TriviaQA dataset I would avoid using the tensorboard metrics, so you I think you will have to either 1) re-run the experiments with the best-weights parameter set or 2) settle for using the end-of-training weights.

**Comment by danishpruthi** [comment]
Thanks for your quick reply. What do you recommend I set the `best_weight` parameter to in `get_triviaqa_train_params` in `ablate_triviaqa.py`?

**Comment by chrisc36** [comment]
Forgot this was still hanging, to answer your setting just leaving it at "None" is fine, thats how our experiments were run. Otherwise setting it to the dev question em or f1 makes the most sense. For example, I think ("dev", "b8/question-text-em") would work.
