### ISSUE TITLE
What happened to UNK?

### ISSUE THREAD

**Issue by obryanlouis** [allenai/document-qa#19]
Hi,

I am using the Elmo model provided in this repo and the UNK token seems to be missing from the squad_train_dev_all_unique_tokens.txt file. I think it is just the last index in the embedding because the embedding has length 106300 while there are 106299 tokens in the file. So, I guess that works for embedding_lookup anyway since the UNK id is left as -1. Is that right?

**Comment by obryanlouis** [comment]
100k words also seems really small (there is no truncation issue with the file right?).

**Comment by chrisc36** [comment]
The Elmo model derives word embeddings by using a character-level CNN on the characters within each word. As such, there is no UNK token. The word-vector file you are looking is a cache of these character-derived word embedding on the SQuAD vocabulary, we use it so we don't have to run the expensive CNN while training on SQuAD.

**Comment by obryanlouis** [comment]
Thank you for the reply. If I am also training (a different model) on SQuAD, should I be using the cache or CNN?

**Comment by chrisc36** [comment]
As long as you are using SQuAD train or dev data, you can use the cache. Otherwise you would have to use the CNN.

**Comment by obryanlouis** [comment]
I got both versions working and I am using the CNN version for training now. The major concern I had with the cached version is that I am using some vocabulary in my own project that has to be mapped to the one in this project, and the cache has a very downsized set of words (about 4% of the words in the comparable vocab) and furthermore the UNK symbol can't be mapped.

One thing that I also noticed, which isn't really related to this issue is that while the CNN make be resource intensive, the code doesn't run the LSTM's using cuDNN, so that could help as well.

I will close this since I am using the CNN version for training.

**Comment by chrisc36** [comment]
Great. It would be great to run the LSTM using cuDNN, but I believe the pre-trained model we have is not compatible with the cuDNN's LSTM implementation. 

You could also consider building your own cache of word vectors with your vocabulary, I haven't had to do this myself but I don't think it should be to hard. You would basically have to run the CNN over all the words in you voc and store the results in the same format.
