### ISSUE TITLE
how to expand span for list of answer items?

### ISSUE THREAD

**Issue by ewagner70** [allenai/document-qa#26]
whenever I ask a question which then shall produce a longer list of items as answer, it mostly/only takes the first item as answer. How can that be extended?

**Comment by chrisc36** [comment]
The demo actually does this, so you could look at qa_system.py so see how. Basically you can use prediction. get_span_scores() for get a score for every possible span, and the post-process that as you want to get the top-k answers

**Comment by chrisc36** [comment]
The Triviaqa data tends to only have short answers, while SQuAD has slightly longer answers, but not up to length 100. As a result all of these models have only been trained to extract short-answers, and its unlikely they will work very well if you want to extract long answers. The only sure-fire way to teach the model to extract longer answers spans would be to train it on a QA dataset with examples of longer answers.

The confidence score is a number optimized during training to ensure the correct answer span has a higher score then any other span within the document. It will not be perfect, especially if you are using the model on data that is very different then the kind the model was trained on.

**Comment by ewagner70** [comment]
Thank you very much for your first explanation - absolutely clear (I feel so stupid right now ...)

the confidence score explanation remains a bit vague ... can you potentially provide a more in depth explanation (provided that's not too much effort for you)?

I circumvent that by providing short (your result) and long answers (whole paragraph) and an ensemble with a Support Vector Machine and cosine similarity ;-) works quite ok, btw ...

**Comment by chrisc36** [comment]
I am glad to hear that its working. For the longer answer on the confidence numbers I can refer you to the paper:

https://arxiv.org/abs/1710.10723, it particular look at Section 3 which about how we designed the confidence scores the model uses.
