### ISSUE TITLE
How to use IndependentBoundsNoAnswerOption ?

### ISSUE THREAD

**Issue by Senhaji-Rhazi-Hamza** [allenai/document-qa#28]
Please we would like to know how to use the IndependentBoundsNoAnswerOption class,  the aim would be to retrain bidaf to perform the task of recognizing wether an answer exist or not for the  a question in a paragrpah,

thank you !

**Comment by chrisc36** [comment]
We don't support an objective function for just recognizing whether an answer exists, however you modify the code `IndependentBoundsNoAnswerOption` to support that case.
