### ISSUE TITLE
Demo idea: Allow users to upload documents

### ISSUE THREAD

**Issue by vshan** [allenai/document-qa#3]
The demo is a delight to use, and I want to congratulate the entire team on this incredible accomplishment of document question answering. What would be even more impressive to the end user would be the ability to upload their own documents and then perform question answering on that.

**Comment by chrisc36** [comment]
I really like this idea, but I can't make promises about when I will get a chance to implement it. I would like to add the demo code to the repo so, at the least, we could accept contributions to it.

**Comment by chrisc36** [comment]
Done! I got inspired and built it. You can now upload documents or write your own text in addition to searching the web.
