### ISSUE TITLE
In the file train_bidaf.py some imports can't be located

### ISSUE THREAD

**Issue by murphp15** [allenai/document-qa#30]
In the file train_bidaf.py some of the imports can't be located. I have searched the codebase and they do not seem to be there? 
The problematic imports are : 
`from docqa.data_processing.paragraph_qa import ContextLenKey, ContextLenBucketedKey, DocumentQaTrainingData
from docqa.squad.squad_eval import SentenceSpanEvaluator, SquadSpanEvaluator, BoundedSquadSpanEvaluator `

**Comment by chrisc36** [comment]
The imports were out of date. I fixed them so the script *should* work, although I haven't re-run the entire thing myself to fully confirm it.
