### ISSUE TITLE
In the class SingleSpanAnswerEncoder a tf placeholder is being assign to a python variable which will never be used. 

### ISSUE THREAD

**Issue by murphp15** [allenai/document-qa#31]
I might be missing something. 
But in the class SingleSpanAnswerEncoder you are assigning tf.placeholder to a field however in the encode section you are overriding this field with np.zeros. 
What was the point in assigning a the tf.placeholder in the first place? 
code below
`
class SingleSpanAnswerEncoder(AnswerEncoder):
    """ Encode the answer as integer coordinates, pick a random answer span if multiple spans exists """

    def __init__(self):
        self.answer_spans = None

    def get_placeholders(self) -> List:
        return [self.answer_spans]

    def init(self, batch_size, context_word_dim):
        self.answer_spans = tf.placeholder('int32', [batch_size, 2], name='answer_spans')

    def encode(self, batch_size, context_len, context_word_dim, batch) -> Dict:
        answer_spans = np.zeros([batch_size, 2], dtype='int32')
        ....
    def __getstate__(self):
        return {}

    def __setstate__(self, state):
        return self.__init__() `

**Comment by chrisc36** [comment]
I am not seeing the override issue you mentioned, in the `encode` method `answer_spans` is a local variable, not the field.
