### ISSUE TITLE
No-answer training

### ISSUE THREAD

**Issue by dusk256** [allenai/document-qa#37]
Why in `choices=["paragraph", "confidence", "shared-norm", "merge", "sigmoid"]` there isn't a "no-answer" option, described in paper?

**Comment by chrisc36** [comment]
Thats a small terminology difference from that paper, in the code "confidence" refers to the "no-answer options" (because the model is trained to produce a confidence probability reflecting the odds the answer occurs in the paragraph).

**Comment by babych-d** [comment]
How can I get this "confidence probabilty" from trained model? 
Now I'm getting confidence value of answer with:
`best_spans, conf = self.sess.run([self.best_spans, self.conf], feed_dict=encoded)`
But how can I get score, that represent if answer occurs in paragraph?

**Comment by chrisc36** [comment]
The `Prediction` object return by the confidence model (`ConfidencePrediction`) include a field `none_prob` which contains that probability.

**Comment by babych-d** [comment]
Thank you!
