### ISSUE TITLE
Can not understand why do this op?

### ISSUE THREAD

**Issue by guotong1988** [allenai/document-qa#4]
`dist_matrix = tf.exp(dist_matrix)`

https://github.com/allenai/document-qa/blob/master/docqa/nn/attention.py#L37

**Comment by chrisc36** [comment]
I added a comment.

This computes softmax with an additional bias term, this allows the model to 'ignore' the memories if needed since the sum of the weights given to each memory can be < 1. The exp is just part of the softmax operation
