### ISSUE TITLE
Getting an error while training the model on TriviaQA Web

### ISSUE THREAD

**Issue by felixgwu** [allenai/document-qa#6]
Hi,
Thank you for sharing this amazing work.

I followed the instructions to pre-process the data and trained the model on the TriviaQA Web.
However, I got an error when it tried to save the model after evaluation.

Here are the preprocessing scripts I ran:
```sh
python docqa/triviaqa/evidence_corpus.py --n_processes 8
python docqa/triviaqa/build_span_corpus.py web --n_processes 8
```
Then I ran:
```sh
python docqa/scripts/ablate_triviaqa.py -n 8 shared-norm-600 save/web-shared-600
```
and got the following error:

```
on epoch=0 batch=1710 step=1710, time=22.648
on epoch=0 batch=1740 step=1740, time=21.728
on epoch=0 batch=1770 step=1770, time=21.884
on epoch=0 batch=1800 step=1800, time=22.147
Checkpointing
Running evaluation...
dev: 100%|████████████████████████████████████| 125/125 [01:40<00:00,  1.70it/s]
Traceback (most recent call last):
  File "docqa/scripts/ablate_triviaqa.py", line 180, in <module>
    main()
  File "docqa/scripts/ablate_triviaqa.py", line 176, in main
    trainer.start_training(data, model, params, eval, model_dir.ModelDir(out), notes)
  File "/home/fw245/clones/document-qa/docqa/trainer.py", line 274, in start_training
    True, train_params, evaluators, out, notes, dry_run)
  File "/home/fw245/clones/document-qa/docqa/trainer.py", line 331, in _train
    evaluators, out, notes, dry_run, start_eval)
  File "/home/fw245/clones/document-qa/docqa/trainer.py", line 624, in _train_async
    val = evaluation.scalars[train_params.best_weights[1]]
KeyError: 'b8/text-f1'
```
I wonder if there is anything wrong when I ran the scripts.

BTW, it takes a long time to load the data. Is there any way to load a tiny part of the dataset for fast debugging?

Thanks in advance.

**Comment by chrisc36** [comment]
Fixed, I introduced an incorrect name in the script when I was cleaning it up. It should be working now.

To run on a sample, you can change:

`data = PreprocessedData(data, extract, train, test, eval_on_verified=False)`

To

`data = PreprocessedData(data, extract, train, test, sample=800, sample_dev=200, eval_on_verified=False)`

and

`params = get_triviaqa_train_params(n_epochs, n_dev, n_train)`

To

`params = get_triviaqa_train_params(n_epochs, None, None)`

**Comment by felixgwu** [comment]
Thanks for your quick response. It's working now.
