### ISSUE TITLE
Test on user documents and questions locally using pre-trained models.

### ISSUE THREAD

**Issue by vinaymundada27** [allenai/document-qa#9]
How can we test on our own documents and corresponding questions using the **pre-trained models**? 
Could you forward us to any specific methods we need to modify or look into?
Thanks a lot.

**Comment by chrisc36** [comment]
Yes, I added a detailed example in:

"docqa/scripts/run_on_user_documents.py"

See the updated README ("User Input") for usage

**Comment by ajay01994** [comment]
Thanks @chrisc36  ,and  your Team  for making documnet Q/A  , currently  it is not supporting PDF as direct input , i assume the PDF needs to be processed in the form of  <title > and < para > ,using your science parse  repo , is there a  way to directly take PDF doc as an input with  built in pdf processing script in your DOC Q /A or  , it will be great if you can do us this favour . Also can you please tell us , that  can Doc QA be used as a search engine , apart from traditonal lucene based elastic search and SOLR serach engines .

Thanks 
Ajay sahu -  Mumbai / BHARAT
